
package soapserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServer", targetNamespace = "http://soapwebserver.habib.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServer {


    /**
     * 
     * @param connection
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Connection")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Connection", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.Connection")
    @ResponseWrapper(localName = "ConnectionResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.ConnectionResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/ConnectionRequest", output = "http://soapwebserver.habib.com/WebServer/ConnectionResponse")
    public String connection(
        @WebParam(name = "connection", targetNamespace = "")
        String connection);

    /**
     * 
     * @param newMessages
     * @param arg1
     */
    @WebMethod(operationName = "NewMessages")
    @RequestWrapper(localName = "NewMessages", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.NewMessages")
    @ResponseWrapper(localName = "NewMessagesResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.NewMessagesResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/NewMessagesRequest", output = "http://soapwebserver.habib.com/WebServer/NewMessagesResponse")
    public void newMessages(
        @WebParam(name = "newMessages", targetNamespace = "")
        String newMessages,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param roomName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMessages")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetMessages", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.GetMessages")
    @ResponseWrapper(localName = "GetMessagesResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.GetMessagesResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/GetMessagesRequest", output = "http://soapwebserver.habib.com/WebServer/GetMessagesResponse")
    public String getMessages(
        @WebParam(name = "roomName", targetNamespace = "")
        String roomName);

    /**
     * 
     * @param users
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListUsers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListUsers", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.ListUsers")
    @ResponseWrapper(localName = "ListUsersResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.ListUsersResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/ListUsersRequest", output = "http://soapwebserver.habib.com/WebServer/ListUsersResponse")
    public String listUsers(
        @WebParam(name = "users", targetNamespace = "")
        String users);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListRooms")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListRooms", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.ListRooms")
    @ResponseWrapper(localName = "ListRoomsResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.ListRoomsResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/ListRoomsRequest", output = "http://soapwebserver.habib.com/WebServer/ListRoomsResponse")
    public String listRooms();

    /**
     * 
     * @param roomName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateNewRooms")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateNewRooms", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.CreateNewRooms")
    @ResponseWrapper(localName = "CreateNewRoomsResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.CreateNewRoomsResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/CreateNewRoomsRequest", output = "http://soapwebserver.habib.com/WebServer/CreateNewRoomsResponse")
    public String createNewRooms(
        @WebParam(name = "roomName", targetNamespace = "")
        String roomName);

    /**
     * 
     * @param roomToJoin
     * @param arg1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JoinRoom")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JoinRoom", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.JoinRoom")
    @ResponseWrapper(localName = "JoinRoomResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.JoinRoomResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/JoinRoomRequest", output = "http://soapwebserver.habib.com/WebServer/JoinRoomResponse")
    public String joinRoom(
        @WebParam(name = "roomToJoin", targetNamespace = "")
        String roomToJoin,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param roomToLeave
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LeaveRoom")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LeaveRoom", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.LeaveRoom")
    @ResponseWrapper(localName = "LeaveRoomResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.LeaveRoomResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/LeaveRoomRequest", output = "http://soapwebserver.habib.com/WebServer/LeaveRoomResponse")
    public String leaveRoom(
        @WebParam(name = "roomToLeave", targetNamespace = "")
        String roomToLeave,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param disconnect
     * @param arg1
     */
    @WebMethod(operationName = "Disconnect")
    @RequestWrapper(localName = "Disconnect", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.Disconnect")
    @ResponseWrapper(localName = "DisconnectResponse", targetNamespace = "http://soapwebserver.habib.com/", className = "soapserver.DisconnectResponse")
    @Action(input = "http://soapwebserver.habib.com/WebServer/DisconnectRequest", output = "http://soapwebserver.habib.com/WebServer/DisconnectResponse")
    public void disconnect(
        @WebParam(name = "disconnect", targetNamespace = "")
        String disconnect,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
